version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "5173:5173"
  api-server:
    image: api-server
    depends_on:
      - postgres
    ports:
    - "3000:3000"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata: